"""Validation rules split into focused modules (RO-31).

This package re-exports all check functions so that validator.py can import
them from a single location.
"""

from .structural import (
    _check_graph_structure,
    _check_covers_graph,
    _check_field_completeness,
    _check_claimed_path_incomplete,
    _check_task_paths_outside_plan_scope,
    _check_implicit_serialization,
    _check_shared_file_verification,
    _check_integration_spine,
    _check_role_constraints,
    _check_early_integration_checkpoint,
    _check_e2e_compile_check,
    _is_cross_task_verifier,
    _check_module_consistency,
    _check_module_dep_cycle,
    _check_module_structure,
    _check_workflow_evaluation_placeholder,
)
from .semantic_defaults import W_SEMANTIC_DEFAULT_PARTIAL_UPDATE, _check_semantic_default_consistency
from .task_granularity import W_TASK_GRANULARITY_COMPRESSION, _check_task_granularity
from .doc_parity import (
    W_DOC_WRITER_CHECKER_SECTION_DRIFT,
    _check_doc_writer_checker_parity,
)
from .coverage import (
    W_INTEGRATION_DORMANT_PATH,
    W_INTEGRATION_IMPORT_ONLY_NO_CALL,
    W_GUARD_AFTER_SIDE_EFFECT,
    W_SILENT_FALLBACK,
    W_VERIFICATION_NO_MAIN_PATH_COMMAND,
    _check_verification_strength,
    _check_verification_no_checks,
    _check_verification_non_gating,
    _check_verification_shallow_checks,
    _check_verification_main_path_command,
    _check_integration_task_shallow_verification,
    _check_integration_claim_evidence,
    _check_integration_call_evidence,
    _check_active_path_reachability,
    _check_observable_fallback,
    _check_guard_ordering,
    _check_dead_verification_command,
    _check_covers_not_exercised,
    _check_failure_path,
    _check_verification_behavior_match,
    _check_duplicate_verification_commands,
    _check_verification_cross_scope,
    _check_covers_verifiability,
    _check_critical_coverage,
    _check_flow_segment_ownership,
    _check_critical_flow_levels,
    _check_critical_flow_worker_only_verification,
    _check_critical_flow_independent_review,
    _check_security_reviewer_assignment,
    _check_security_reviewer_assignment_issues,
    _check_issue_coverage,
    _check_task_addresses_disjoint,
    _check_mock_tests_completeness,
    _check_forbidden_flows,
    _check_forbidden_flow_field_coverage,
    _check_status_code_drift,
    _check_status_code_implementation_drift,
    _check_finding_refs,
    _check_suppress_flows,
    _check_covers_unknown_flow,
    _check_state_unknown_task_ref,
    _check_state_task_status_conflict,
    _check_running_task_claims,
    _check_af_verification_gate_bypass,
    _check_duplicate_ids,
    _check_flow_test_created_by_unknown,
    _check_flow_id_cross_namespace,
    _check_critical_flow_no_entrypoints,
    _check_critical_declaration_outside_scope,
    _check_suppress_unused,
    _check_plan_scope_unused,
    _check_claimed_test_not_exercised,
    _check_full_regression_override_risk,
    _has_issue_codes,
    _check_batch_e2e_command,
)
from .agentflow_invariants import _check_agentflow_invariants
from .contracts import (
    _check_contracts,
    _check_contract_verification_coverage,
    _check_consume_provider_unresolved,
    _check_contract_dep_alignment,
    _check_consumer_from_provides,
    _check_contract_kind_mismatch,
    _check_cross_task_io_contracts,
)

from . import discipline
from .discipline import (
    _check_aegis_discipline,
    check_rule_registration_completeness,
    collect_discipline_issues,
)
from .security import (
    _NON_SUPPRESSIBLE_WHEN_SECURITY,
    _check_auth_boundary_type_safety,
    _check_identity_surface_privilege,
    _non_suppressible_codes,
    _check_rbac_flow_auth_coverage,
    _check_rbac_write_endpoint_coverage,
    _check_reviewer_signoff,
    _check_security_critical_flow_suppressed,
    _check_security_recipes,
    _check_signoff_structure,
    _check_state_machine_concurrency_safety,
    _check_state_machine_concurrency_safety_issues,
    _plan_has_security_critical_flow,
)


def get_all_rules():
    """Return all rule functions for discovery/testing."""
    return [
        # structural
        _check_graph_structure,
        _check_covers_graph,
        _check_field_completeness,
        _check_claimed_path_incomplete,
        _check_task_paths_outside_plan_scope,
        _check_implicit_serialization,
        _check_shared_file_verification,
        _check_integration_spine,
        _check_role_constraints,
        _check_early_integration_checkpoint,
        _check_e2e_compile_check,
        _check_module_dep_cycle, _check_semantic_default_consistency,
        _check_module_structure,
        _check_task_granularity,
        _check_doc_writer_checker_parity,
        _check_workflow_evaluation_placeholder,
        # coverage
        _check_verification_strength,
        _check_verification_no_checks,
        _check_verification_non_gating,
        _check_verification_shallow_checks,
        _check_verification_main_path_command,
        _check_integration_task_shallow_verification,
        _check_integration_claim_evidence,
        _check_integration_call_evidence,
        _check_active_path_reachability,
        _check_observable_fallback,
        _check_guard_ordering,
        _check_dead_verification_command,
        _check_covers_not_exercised,
        _check_failure_path,
        _check_verification_behavior_match,
        _check_duplicate_verification_commands,
        _check_verification_cross_scope,
        _check_covers_verifiability,
        _check_critical_coverage,
        _check_flow_segment_ownership,
        _check_critical_flow_levels,
        _check_critical_flow_worker_only_verification,
        _check_critical_flow_independent_review,
        _check_security_reviewer_assignment_issues,
        _check_issue_coverage,
        _check_task_addresses_disjoint,
        _check_mock_tests_completeness,
        _check_forbidden_flows,
        _check_forbidden_flow_field_coverage,
        _check_status_code_drift,
        _check_status_code_implementation_drift,
        _check_finding_refs,
        _check_suppress_flows,
        _check_covers_unknown_flow,
        _check_state_unknown_task_ref,
        _check_state_task_status_conflict,
        _check_running_task_claims,
        _check_af_verification_gate_bypass,
        _check_duplicate_ids,
        _check_flow_test_created_by_unknown,
        _check_flow_id_cross_namespace,
        _check_critical_flow_no_entrypoints,
        _check_critical_declaration_outside_scope,
        _check_suppress_unused,
        _check_plan_scope_unused,
        _check_claimed_test_not_exercised,
        _check_full_regression_override_risk,
        # v56
        _check_agentflow_invariants,
        # contracts
        _check_contracts,
        _check_contract_verification_coverage,
        _check_consume_provider_unresolved,
        _check_contract_dep_alignment,
        _check_consumer_from_provides,
        _check_contract_kind_mismatch,
        # discipline
        collect_discipline_issues,
        # security
        _check_rbac_flow_auth_coverage,
        _check_rbac_write_endpoint_coverage,
        _check_auth_boundary_type_safety,
        _check_identity_surface_privilege,
        _check_reviewer_signoff,
        _check_signoff_structure,
        _check_state_machine_concurrency_safety_issues,
        _check_security_critical_flow_suppressed,
        _check_security_recipes,
    ]


__all__ = [
    "get_all_rules",
    "discipline",
    "collect_discipline_issues",
    "check_rule_registration_completeness",
    "_check_graph_structure",
    "_check_covers_graph",
    "_check_field_completeness",
    "_check_claimed_path_incomplete",
    "_check_task_paths_outside_plan_scope",
    "_check_implicit_serialization",
    "_check_shared_file_verification",
    "_check_integration_spine",
    "_check_role_constraints",
    "_check_early_integration_checkpoint",
    "_check_e2e_compile_check",
    "_is_cross_task_verifier",
    "_check_module_dep_cycle",
    "_check_module_structure",
    "_check_workflow_evaluation_placeholder", "_check_semantic_default_consistency",
    "_check_task_granularity",
    "_check_doc_writer_checker_parity",
    "_check_verification_strength",
    "_check_verification_no_checks",
    "_check_verification_non_gating",
    "_check_verification_shallow_checks",
    "_check_verification_main_path_command",
    "_check_integration_task_shallow_verification",
    "_check_integration_claim_evidence",
    "_check_integration_call_evidence",
    "_check_active_path_reachability",
    "_check_observable_fallback",
    "_check_guard_ordering",
    "W_INTEGRATION_IMPORT_ONLY_NO_CALL",
    "W_INTEGRATION_DORMANT_PATH",
    "W_GUARD_AFTER_SIDE_EFFECT",
    "W_SILENT_FALLBACK",
    "W_VERIFICATION_NO_MAIN_PATH_COMMAND", "W_SEMANTIC_DEFAULT_PARTIAL_UPDATE",
    "W_TASK_GRANULARITY_COMPRESSION",
    "W_DOC_WRITER_CHECKER_SECTION_DRIFT",
    "_check_dead_verification_command",
    "_check_covers_not_exercised",
    "_check_failure_path",
    "_check_verification_behavior_match",
    "_check_duplicate_verification_commands",
    "_check_verification_cross_scope",
    "_check_covers_verifiability",
    "_check_critical_coverage",
    "_check_flow_segment_ownership",
    "_check_critical_flow_levels",
    "_check_critical_flow_worker_only_verification",
    "_check_critical_flow_independent_review",
    "_check_security_reviewer_assignment",
    "_check_security_reviewer_assignment_issues",
    "_check_issue_coverage",
    "_check_task_addresses_disjoint",
    "_check_mock_tests_completeness",
    "_check_forbidden_flows",
    "_check_forbidden_flow_field_coverage",
    "_check_status_code_drift",
    "_check_status_code_implementation_drift",
    "_check_finding_refs",
    "_check_suppress_flows",
    "_check_covers_unknown_flow",
    "_check_state_unknown_task_ref",
    "_check_state_task_status_conflict",
    "_check_running_task_claims",
    "_check_af_verification_gate_bypass",
    "_check_duplicate_ids",
    "_check_flow_test_created_by_unknown",
    "_check_flow_id_cross_namespace",
    "_check_critical_flow_no_entrypoints",
    "_check_critical_declaration_outside_scope",
    "_check_suppress_unused",
    "_check_plan_scope_unused",
    "_check_claimed_test_not_exercised",
    "_check_full_regression_override_risk",
    "_check_agentflow_invariants",
    "_has_issue_codes",
    "_check_batch_e2e_command",
    "_check_contracts",
    "_check_contract_verification_coverage",
    "_check_consume_provider_unresolved",
    "_check_contract_dep_alignment",
    "_check_consumer_from_provides",
    "_check_contract_kind_mismatch",
    "_check_aegis_discipline",
    "_NON_SUPPRESSIBLE_WHEN_SECURITY",
    "_non_suppressible_codes",
    "_plan_has_security_critical_flow",
    "_check_auth_boundary_type_safety",
    "_check_rbac_flow_auth_coverage",
    "_check_rbac_write_endpoint_coverage",
    "_check_identity_surface_privilege",
    "_check_reviewer_signoff",
    "_check_signoff_structure",
    "_check_state_machine_concurrency_safety",
    "_check_state_machine_concurrency_safety_issues",
    "_check_security_critical_flow_suppressed",
    "_check_security_recipes",
]
